sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
cache:
  - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install gulp mgit2 lerna codeclimate-test-reporter
  - npm install @ckeditor/ckeditor5-dev-tests @ckeditor/ckeditor5-dev-lint
  - ckeditor5-dev-tests-install-dependencies
script:
  - ckeditor5-dev-tests-travis
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
